In [3]:
import pandas as pd

In [4]:
print(pd.__version__)

1.4.4


In [18]:
A = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

In [19]:
A.values

array([0.25, 0.5 , 0.75, 1.  ])

In [20]:
type(A.values)

numpy.ndarray

In [21]:
type(A)

pandas.core.series.Series

In [22]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [23]:
A['a']

0.25

In [24]:
A['b']

0.5

In [25]:
A['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [27]:
grads_dict = {'A':4, 'B':3.5, 'C':3, 'D':2.5}
grads = pd.Series(grads_dict)

In [28]:
grads.values

array([4. , 3.5, 3. , 2.5])

In [29]:
marks_dict = {'A':85, 'B':75, 'C':65, 'D':55}
marks = pd.Series(marks_dict)

In [30]:
marks.values

array([85, 75, 65, 55])

In [31]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [32]:
marks['A']

85

In [33]:
marks[0:2]

A    85
B    75
dtype: int64

### Pandas (Data Frame)

In [41]:
grades_dict = {'A':4, 'A-':3.5, 'B':3, 'B-':2.5, 'C':2}
grades = pd.Series(grades_dict)

In [42]:
grades

A     4.0
A-    3.5
B     3.0
B-    2.5
C     2.0
dtype: float64

In [43]:
marks_dict = {'A':85, 'A-':80, 'B':75, 'B-':70, 'C':65}
marks = pd.Series(marks_dict)

In [44]:
marks

A     85
A-    80
B     75
B-    70
C     65
dtype: int64

In [39]:
rs = pd.DataFrame({'grades':grades, 'marks':marks})

In [40]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [46]:
rs.T

A    A-     B    B-     C
grades   4.0   3.5   3.0   2.5   2.0
marks   85.0  80.0  75.0  70.0  65.0

In [47]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [48]:
rs.values

array([[ 4. , 85. ],
       [ 3.5, 80. ],
       [ 3. , 75. ],
       [ 2.5, 70. ],
       [ 2. , 65. ]])

In [49]:
rs.values[2,0]

3.0

In [50]:
rs.columns

Index(['grades', 'marks'], dtype='object')

In [51]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [54]:
rs['ScaledMarks'] = 100*(rs['marks']/90)

In [55]:
rs

grades  marks  ScaledMarks
A      4.0     85    94.444444
A-     3.5     80    88.888889
B      3.0     75    83.333333
B-     2.5     70    77.777778
C      2.0     65    72.222222

In [57]:
del rs['ScaledMarks']

In [58]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [59]:
G = rs[rs['marks']>70]

In [60]:
G

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75

### Pandas (NaN)

In [66]:
A = pd.DataFrame([{'a':1, 'b':2},{'b':3, 'c':4}])

In [67]:
A

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [68]:
A.fillna(0)

a  b    c
0  1.0  2  0.0
1  0.0  3  4.0

In [72]:
B = A

In [73]:
B

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [74]:
B.dropna()

Empty DataFrame
Columns: [a, b, c]
Index: []

In [75]:
A

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

### Pandas(Indexing)

In [76]:
A = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

In [77]:
A[1]

'a'

In [78]:
A[1:3]

3    b
5    c
dtype: object

In [80]:
A.loc[1:3]

1    a
3    b
dtype: object

In [82]:
A.iloc[1:3]

3    b
5    c
dtype: object

In [83]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [84]:
rs.iloc[2,:]

grades     3.0
marks     75.0
Name: B, dtype: float64

In [85]:
rs.iloc[::-1,:]

grades  marks
C      2.0     65
B-     2.5     70
B      3.0     75
A-     3.5     80
A      4.0     85

### Pandas (csv files)

In [88]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
df = pd.read_csv('/home/blackd3vil/Desktop/Samsung-College-Training/covid_19_data.csv')

In [89]:
df.head()

date location_key  new_confirmed  new_deceased  new_recovered  \
0  2020-01-01           AD            0.0           0.0            NaN   
1  2020-01-02           AD            0.0           0.0            NaN   
2  2020-01-03           AD            0.0           0.0            NaN   
3  2020-01-04           AD            0.0           0.0            NaN   
4  2020-01-05           AD            0.0           0.0            NaN   

   new_tested  cumulative_confirmed  cumulative_deceased  \
0         NaN                   0.0                  0.0   
1         NaN                   0.0                  0.0   
2         NaN                   0.0                  0.0   
3         NaN                   0.0                  0.0   
4         NaN                   0.0                  0.0   

   cumulative_recovered  cumulative_tested  
0                   NaN                NaN  
1                   NaN                NaN  
2                   NaN                NaN  
3                   NaN                NaN  
4                   NaN                NaN

In [92]:
df.drop(['date', 'location_key'], axis=1, inplace=True)

In [93]:
df.head()

new_confirmed  new_deceased  new_recovered  new_tested  \
0            0.0           0.0            NaN         NaN   
1            0.0           0.0            NaN         NaN   
2            0.0           0.0            NaN         NaN   
3            0.0           0.0            NaN         NaN   
4            0.0           0.0            NaN         NaN   

   cumulative_confirmed  cumulative_deceased  cumulative_recovered  \
0                   0.0                  0.0                   NaN   
1                   0.0                  0.0                   NaN   
2                   0.0                  0.0                   NaN   
3                   0.0                  0.0                   NaN   
4                   0.0                  0.0                   NaN   

   cumulative_tested  
0                NaN  
1                NaN  
2                NaN  
3                NaN  
4                NaN

In [96]:
df.rename(columns={'new_confirmed':'confirmed', 'new_deceased':'deceased'}, inplace=True)

In [97]:
df.head()

confirmed  deceased  new_recovered  new_tested  cumulative_confirmed  \
0        0.0       0.0            NaN         NaN                   0.0   
1        0.0       0.0            NaN         NaN                   0.0   
2        0.0       0.0            NaN         NaN                   0.0   
3        0.0       0.0            NaN         NaN                   0.0   
4        0.0       0.0            NaN         NaN                   0.0   

   cumulative_deceased  cumulative_recovered  cumulative_tested  
0                  0.0                   NaN                NaN  
1                  0.0                   NaN                NaN  
2                  0.0                   NaN                NaN  
3                  0.0                   NaN                NaN  
4                  0.0                   NaN                NaN

In [98]:
# df.['Date'] = pd.to_datetime(df['Date'])

In [99]:
df.describe()

confirmed      deceased  new_recovered    new_tested  \
count  1.247580e+07  1.166714e+07   3.980462e+06  3.194489e+06   
mean   1.111905e+02  1.274817e+00   2.104549e+02  2.509508e+03   
std    1.165983e+04  8.808127e+01   1.898989e+04  2.955847e+05   
min   -5.045418e+06 -6.381100e+04  -1.001683e+07 -3.541552e+08   
25%    0.000000e+00  0.000000e+00   0.000000e+00  1.000000e+00   
50%    1.000000e+00  0.000000e+00   0.000000e+00  7.000000e+00   
75%    1.100000e+01  0.000000e+00   5.000000e+00  5.200000e+01   
max    5.047094e+06  6.383000e+04   9.967355e+06  3.541856e+08   

       cumulative_confirmed  cumulative_deceased  cumulative_recovered  \
count          1.232704e+07         1.147482e+07          3.991157e+06   
mean           3.539969e+04         5.874310e+02          6.655680e+04   
std            6.135014e+05         9.228857e+03          1.572899e+06   
min            0.000000e+00         0.000000e+00         -3.000000e+00   
25%            2.020000e+02         3.000000e+00          0.000000e+00   
50%            1.034000e+03         1.800000e+01          7.000000e+00   
75%            5.002000e+03         8.100000e+01          3.099000e+03   
max            9.244050e+07         1.005195e+06          2.345841e+08   

       cumulative_tested  
count       3.012920e+06  
mean        9.057159e+05  
std         1.518347e+07  
min         0.000000e+00  
25%         3.460000e+02  
50%         1.890000e+03  
75%         1.508900e+04  
max         9.214000e+09

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12525825 entries, 0 to 12525824
Data columns (total 8 columns):
 #   Column                Dtype  
---  ------                -----  
 0   confirmed             float64
 1   deceased              float64
 2   new_recovered         float64
 3   new_tested            float64
 4   cumulative_confirmed  float64
 5   cumulative_deceased   float64
 6   cumulative_recovered  float64
 7   cumulative_tested     float64
dtypes: float64(8)
memory usage: 764.5 MB


In [102]:
df = df.fillna('NA')

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12525825 entries, 0 to 12525824
Data columns (total 8 columns):
 #   Column                Dtype 
---  ------                ----- 
 0   confirmed             object
 1   deceased              object
 2   new_recovered         object
 3   new_tested            object
 4   cumulative_confirmed  object
 5   cumulative_deceased   object
 6   cumulative_recovered  object
 7   cumulative_tested     object
dtypes: object(8)
memory usage: 764.5+ MB


In [105]:
df.head(20)

confirmed deceased new_recovered new_tested cumulative_confirmed  \
0        0.0      0.0            NA         NA                  0.0   
1        0.0      0.0            NA         NA                  0.0   
2        0.0      0.0            NA         NA                  0.0   
3        0.0      0.0            NA         NA                  0.0   
4        0.0      0.0            NA         NA                  0.0   
5        0.0      0.0            NA         NA                  0.0   
6        0.0      0.0            NA         NA                  0.0   
7        0.0      0.0            NA         NA                  0.0   
8        0.0      0.0            NA         NA                  0.0   
9        0.0      0.0            NA         NA                  0.0   
10       0.0      0.0            NA         NA                  0.0   
11       0.0      0.0            NA         NA                  0.0   
12       0.0      0.0            NA         NA                  0.0   
13       0.0      0.0            NA         NA                  0.0   
14       0.0      0.0            NA         NA                  0.0   
15       0.0      0.0            NA         NA                  0.0   
16       0.0      0.0            NA         NA                  0.0   
17       0.0      0.0            NA         NA                  0.0   
18       0.0      0.0            NA         NA                  0.0   
19       0.0      0.0            NA         NA                  0.0   

   cumulative_deceased cumulative_recovered cumulative_tested  
0                  0.0                   NA                NA  
1                  0.0                   NA                NA  
2                  0.0                   NA                NA  
3                  0.0                   NA                NA  
4                  0.0                   NA                NA  
5                  0.0                   NA                NA  
6                  0.0                   NA                NA  
7                  0.0                   NA                NA  
8                  0.0                   NA                NA  
9                  0.0                   NA                NA  
10                 0.0                   NA                NA  
11                 0.0                   NA                NA  
12                 0.0                   NA                NA  
13                 0.0                   NA                NA  
14                 0.0                   NA                NA  
15                 0.0                   NA                NA  
16                 0.0                   NA                NA  
17                 0.0                   NA                NA  
18                 0.0                   NA                NA  
19                 0.0                   NA                NA

In [ ]:
df2 = df.groupby('new_recovered')[['confirmed', 'deceased', 'new_recovered', 'new_tested']].sum().reset_index()

In [ ]:
df2