### Practice Data Structure

In [2]:
"""Let say you are a teacher and you have different student records
containing id of a student and the marks list in each subject where different students have taken different number of subjects. All 
these records are in hard copy. You want to enter all the data in computer 
and want to compute the average marks of each student and display"""

'Let say you are a teacher and you have different student records\ncontaining id of a student and the marks list in each subject where different students have taken different number of subjects. All \nthese records are in hard copy. You want to enter all the data in computer \nand want to compute the average marks of each student and display'

In [7]:
def getDataFromUser():
    D = {} # Dictionary Container
    while True:
        studentId = input("Enter student ID: ")
        marksList = input("Enter the marks by comma separated values: ")
        moreStudent = input('Enter "no" to quit: ')
        if studentId in D:
            print(studentId, " is already inserted")
        else:
            D[studentId] = marksList.split(",")
        if moreStudent.lower() == "no":
            return D
        
            

In [8]:
studentData = getDataFromUser()

Enter student ID: 12
Enter the marks by comma separated values: 45, 67, 86,45, 68
Enter "no" to quit: yes
Enter student ID: 13
Enter the marks by comma separated values: 86, 45, 86, 46, 66
Enter "no" to quit: no


In [9]:
studentData

{'12': ['45', ' 67', ' 86', '45', ' 68'],
 '13': ['86', ' 45', ' 86', ' 46', ' 66']}

In [10]:
def getAvgMarks(D):
    avgMarks = {}
    for x in D:
        L = D[x]
        s = 0
        for marks in L:
            s += int(marks)
        avgMarks[x] = s/len(L) 
        return avgMarks

In [11]:
avgM = getAvgMarks(studentData)

In [12]:
for x in avgM:
    print("Student :", x, " got avg Marks as: ", avgM[x])

Student : 12  got avg Marks as:  62.2


### Numpy (Indexing)

In [14]:
import numpy as np

In [15]:
A = np.arange(100)

In [16]:
B = A[[3, 5, 6]]

In [17]:
B

array([3, 5, 6])

In [19]:
B[0] = 4

In [20]:
B

array([4, 5, 6])

In [21]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
B = A[A<40]

In [23]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [29]:
B = A[(A<40) & (A>30)]

In [27]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [30]:
# &, and
# |, or
# ~, not

### Numpy (Broadcasting)

In [31]:
A = np.round(10*np.random.rand(2,3))

In [32]:
A

array([[5., 5., 3.],
       [8., 5., 3.]])

In [33]:
A+3

array([[ 8.,  8.,  6.],
       [11.,  8.,  6.]])

In [34]:
A+(np.arange(2).reshape(2,1))

array([[5., 5., 3.],
       [9., 6., 4.]])

In [35]:
A

array([[5., 5., 3.],
       [8., 5., 3.]])

In [36]:
B = np.round(10*np.random.rand(2,3))

In [37]:
A

array([[5., 5., 3.],
       [8., 5., 3.]])

In [38]:
B

array([[3., 6., 4.],
       [3., 9., 6.]])

In [39]:
C = np.hstack((A,B))

In [40]:
C

array([[5., 5., 3., 3., 6., 4.],
       [8., 5., 3., 3., 9., 6.]])

In [41]:
A = np.random.permutation(np.arange(10))

In [42]:
A

array([1, 4, 5, 0, 3, 6, 7, 8, 9, 2])

In [45]:
np.sort(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
A.sort()

In [49]:
A = A[::-1]

In [50]:
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [53]:
A = np.array(["abc", "howare you", "u756", '13er'])

In [54]:
A.sort()

In [55]:
A

array(['13er', 'abc', 'howare you', 'u756'], dtype='<U10')

### Numpy (Speed: ufuncs)

In [57]:
b = np.random.rand(1000000)
%timeit sum(b)
%timeit np.sum(b)

66.9 ms ± 1.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
546 µs ± 9.86 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [59]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s

In [61]:
%timeit mySum(B)

2.44 µs ± 28.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
